"""Config -> Asterisk include files, nftables ruleset and prompt list (aivoicemail generate).

Outputs (relative to [paths].generated_dir):
  asterisk/pjsip-trunk.conf      UDP transport, the IP-identified trunk endpoint, identify sections
  asterisk/extensions-lines.conf DID lookup, one context per line, the record context
  asterisk/cdr.conf              CDR CSV on/off ([retention].cdr)
  nftables/aivoicemail.nft       host firewall: SIP/RTP only from the trunk ranges
  prompts.txt                    the prompt names render-prompts produces (overrides/<name>.wav)
Every value written here was validated by config.load (digits-only DIDs, CIDRs, line ids)."""
import ipaddress
from pathlib import Path

from . import prompts as prompts_mod

HEADER = "; generated by aivoicemail generate - do not edit"
RTP_PORTS = "10000-20000"  # asterisk/etc/rtp.conf
SPOOL_TMP = "/srv/aivoicemail/spool/tmp"


def pjsip_trunk(cfg) -> str:
    t = cfg.trunk
    out = [HEADER, "", "[transport-udp]", "type = transport", "protocol = udp", f"bind = {t.bind}"]
    if t.public_ip:
        out += [f"external_signaling_address = {t.public_ip}", f"external_media_address = {t.public_ip}"]
    if t.local_net:
        out.append(f"local_net = {t.local_net}")
    out += ["", "[trunk]", "type = endpoint", "transport = transport-udp", "context = from-trunk", "disallow = all",
            "allow = alaw,ulaw", "dtmf_mode = auto", "direct_media = no", "rtp_symmetric = yes", "force_rport = yes",
            "rewrite_contact = yes", "allow_subscribe = no", "send_pai = no", "trust_id_inbound = no"]
    if t.media_address:
        out += [f"media_address = {t.media_address}", "bind_rtp_to_media_address = yes"]
    out += ["", "[trunk-identify]", "type = identify", "endpoint = trunk", "match = " + ",".join(t.signalling_ranges)]
    if t.allow_local_test:
        out += ["", "[trunk-identify-local]", "type = identify", "endpoint = trunk", "match = 127.0.0.1/32"]
    return "\n".join(out) + "\n"


def _line_context(line) -> list[str]:
    ctx = f"line-{line.id}"
    lang = "auto" if line.has_menu else line.menu[0]
    out = [f"[{ctx}]", f"exten => s,1,Set(VM_LINE={line.id})", f" same => n,Set(VM_DID={line.did})",
           f" same => n,Set(VM_LANG={lang})", " same => n,Set(VM_START=${EPOCH})",
           " same => n,Set(CHANNEL(hangup_handler_push)=vm-finalize,s,1)", " same => n,Answer()",
           " same => n,Wait(0.5)"]
    if not line.has_menu:
        return out + [f" same => n,Playback(vm/{line.id}-notice-{lang})", " same => n,Goto(vm-record,s,1)"]
    out += [f" same => n,Background(vm/{line.id}-menu)", " same => n,WaitExten(5)"]
    for digit, menu_lang in enumerate(line.menu, start=1):
        out += [f"exten => {digit},1,Set(VM_LANG={menu_lang})", f" same => n,Playback(vm/{line.id}-notice-{menu_lang})",
                " same => n,Goto(vm-record,s,1)"]
    if line.default_language == "auto":
        out.append(f"exten => t,1,Playback(vm/{line.id}-notice-auto)")
    else:
        out += [f"exten => t,1,Set(VM_LANG={line.default_language})",
                f" same => n,Playback(vm/{line.id}-notice-{line.default_language})"]
    out += [" same => n,Goto(vm-record,s,1)", f"exten => i,1,Goto({ctx},t,1)"]
    return out


def extensions_lines(cfg) -> str:
    out = [HEADER, "", "[did-lookup]"]
    for i, line in enumerate(cfg.lines):
        prefix = "exten => s,1," if i == 0 else " same => n,"
        out.append(f'{prefix}GotoIf($["${{D}}" = "{line.did}"]?line-{line.id},s,1)')
    out.append(" same => n,Hangup(1)")
    for line in cfg.lines:
        out += [""] + _line_context(line)
    r = cfg.recording
    out += ["", "[vm-record]", "exten => s,1,Set(VM_RECORDED=1)",
            f" same => n,Record({SPOOL_TMP}/${{UNIQUEID}}.wav,{r.silence_seconds},{r.max_seconds},k)",
            " same => n,Playback(vm/${VM_LINE}-thanks-${VM_LANG})", " same => n,Hangup()"]
    return "\n".join(out) + "\n"


def cdr_conf(cfg) -> str:
    if not cfg.retention.cdr:
        return f"{HEADER}\n\n[general]\nenable = no\n"
    return (f"{HEADER}\n; CDR CSV (metadata only) in cdr-csv/Master.csv, rotated by deploy/logrotate/aivoicemail-cdr\n\n"
            "[general]\nenable = yes\nunanswered = yes\ncongestion = yes\n\n"
            "[csv]\nusegmtime = yes\nloguniqueid = yes\nloguserfield = no\naccountlogs = no\n")


def _split(ranges):
    nets = [ipaddress.ip_network(r) for r in ranges]
    return [str(n) for n in nets if n.version == 4], [str(n) for n in nets if n.version == 6]


def nftables(cfg) -> str:
    sig4, sig6 = _split(cfg.trunk.signalling_ranges)
    med4, med6 = _split(cfg.trunk.media_ranges)
    sip = cfg.trunk.sip_port
    out = ["#!/usr/sbin/nft -f",
           "# generated by aivoicemail generate - do not edit",
           "# Own table: other tables and chains stay untouched. A packet must be accepted by every base chain",
           "# on the input hook, so this table lists everything the host needs: add management ports under",
           "# [firewall] in the config and re-run generate. Apply with the timed rollback in docs/install.md.",
           "table inet aivoicemail",
           "delete table inet aivoicemail",
           "table inet aivoicemail {"]
    for name, kind, elements in (("trunk_sig_v4", "ipv4_addr", sig4), ("trunk_sig_v6", "ipv6_addr", sig6),
                                 ("trunk_media_v4", "ipv4_addr", med4), ("trunk_media_v6", "ipv6_addr", med6)):
        if elements:
            out += [f"  set {name} {{", f"    type {kind}", "    flags interval",
                    "    elements = { " + ", ".join(elements) + " }", "  }"]
    out += ["  chain input {", "    type filter hook input priority filter; policy drop;", '    iif "lo" accept',
            "    ct state established,related accept", "    ct state invalid drop", "    ip protocol icmp accept",
            "    meta l4proto ipv6-icmp accept", "    udp sport 67 udp dport 68 accept"]
    out += [f"    tcp dport {p} accept" for p in cfg.firewall.allow_tcp]
    out += [f"    udp dport {p} accept" for p in cfg.firewall.allow_udp]
    if sig4:
        out.append(f"    ip saddr @trunk_sig_v4 udp dport {sip} accept")
    if sig6:
        out.append(f"    ip6 saddr @trunk_sig_v6 udp dport {sip} accept")
    if med4:
        out.append(f"    ip saddr @trunk_media_v4 udp dport {RTP_PORTS} accept")
    if med6:
        out.append(f"    ip6 saddr @trunk_media_v6 udp dport {RTP_PORTS} accept")
    out += ["  }", "}"]
    return "\n".join(out) + "\n"


def files(cfg) -> dict[str, str]:
    return {
        "asterisk/pjsip-trunk.conf": pjsip_trunk(cfg),
        "asterisk/extensions-lines.conf": extensions_lines(cfg),
        "asterisk/cdr.conf": cdr_conf(cfg),
        "nftables/aivoicemail.nft": nftables(cfg),
        "prompts.txt": "\n".join(prompts_mod.prompt_names(cfg)) + "\n",
    }


def write_all(cfg, out_dir) -> list[Path]:
    written = []
    for rel, content in files(cfg).items():
        path = Path(out_dir) / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        written.append(path)
    return written
